### ISSUE TITLE
Zones not updating in Smartthings

### ISSUE THREAD

**Issue by jag4666** [nutechsoftware/alarmdecoder-smartthings#23]
Hi there,

I have followed the install to a tee. the zone states are not updating (both hardwired and wireless) in the smart things app. I have uninstalled rebooted (both hub and pi) and re-installed with no luck. Webapp does update and is  reflective of zone faulting.

Just uninstalled a former version from smart things and did not encounter any issues with the former version previously loaded.

**Comment by Nu11u5** [comment]
I had to go into the AlarmDecoder webapp > Settings > Notification and add a new notification of type "UPNP Push" (no other settings) before SmartThings would show states updating in real time.

Also, earlier I ran the webapp diagnostics and saw that the python module "miniupnpc" was missing.  I installed it by running `sudo pip install miniupnpc` and then rebooting the host.  I'm not 100% sure this affected the webapp notification functionality since I didn't test UPNP Push before hand but it seems likely.

**Comment by magimat** [comment]
Hi, I have the exact same problem. Everything is up, but I can't get the UPNP notification to work. Tried installing miniupnpc but it didnt help.

Also, I can confirm UPNP is enabled on my router.  

What am I missing??

**Comment by jag4666** [comment]
Anything further on this?

**Comment by dcmeglio** [comment]
@jag4666 @magimat either of you solve this? I'm having the same issue, UPNP is not working.

**Comment by f34rdotcom** [comment]
I am not able to reproduce this. I have had people call and get support for this type of issue but it is usually an obscure problem such as the ST hub and AD2PI are on different networks. @dcmeglio if you contact me at my desk phone or over support email I can probably figure it out. Just an FYI the master branch was just updated and it did contain 2 small but critical documentation errors on what device handler code.

**Comment by dcmeglio** [comment]
@f34rdotcom My issue was resolved. I had something configured wrong. That coupled with the fact that the webapp seems to always fail on UPNP testing made me think it was related

**Comment by f34rdotcom** [comment]
Dev branch test for upnp just shows pass.
