### ISSUE TITLE
API Status Message for Bypassed Zones

### ISSUE THREAD

**Issue by automatorCoder** [nutechsoftware/alarmdecoder-smartthings#39]
Current API reports zones that are faulted but nothing is reported about zones that are bypassed. It would be great if the bypassed zones were reported like the zones faulted.

**Comment by jscongdon** [comment]
Personally, I'd like to see the bypassed zones on a separate page rather than along with the faulted zones. This page could also allow you to un-bypass individual zones.
I would also like to see a verification message before bypassing a zone. I've accidentally bypassed zones from an accidental touch on a mobile device.
