### ISSUE TITLE
Adding Armed state to REST API

### ISSUE THREAD

**Issue by automatorCoder** [nutechsoftware/alarmdecoder-smartthings#41]
When you arm the alarm, the arming mode changes to the type of arming selected (e.g., STAY). For example, when I arm my alarm to STAY, the panel_armed_stay booleans flips to true even though the panel is not _**truly**_ armed. When you press an arming mode the alarm goes into a countdown so the alarm is not armed until the end of this countdown.

Checking the bit field, position 3 flips to 1 immediately after pressing the arming button

```
10000001000000003A ready
00110301000010003A arming button pressed
00100001000010003A countdown complete, armed
```
Seems the only thing that notates actual arming is the keypad message

When arming, the Alphanumeric Keypad Message shows **ARMED *INSTANT* You may exit now**

After the countdown is complete, the Alphanumeric Keypad Message shows **ARMED *INSTANT***

Not sure this is doable but wanted to ask. I guess people can assume that the alarm is armed after they press the arming button (eg, Night, Away, Stay, etc.) even though the countdown is not done.

**Comment by f34rdotcom** [comment]
Yes for EXIT it does look at TEXT no data bits exist on the panel for this state
[See here](https://github.com/nutechsoftware/alarmdecoder/blob/bc9371ec268afe84fc67db3f38ce1dc8ff6c7f7a/alarmdecoder/decoder.py#L789
)

The ARM HOME BIT-3 should turn on as soon as the panel arming starts.
https://www.alarmdecoder.com/wiki/index.php/Protocol#Bit_field

If the panel had "MAY EXIT NOW" it should have triggered the flag and at least the data available to the SmartThings code would have indicated exit was in process. 

So I am confused by the details you provided. BIT-3 instantly shows the panel arming state just as a real keypad would have its arming LED turn RED. So we know the panel is arming/armed. It is however as you noted not fully armed not till the end of the exit cycle. What we are using the ALPHA keypad message for in this case is the EXIT mode state because nothing exists in section #1 of the API for this state.

To be more accurate the GUI needs to show "ARMED INSTANT(EXIT-NOW)" or "ARMED MAX(EXIT-NOW)"

**Comment by automatorCoder** [comment]
Thank you this provides clarification. Interesting that alarm panel makers would not have something in the bit-3 that distinguished arming from armed.
